name: Web Build + Deployment to GitHub Pages 

on:
  push:
    branches: 
      - main
      - gh-pages
  pull_request:
    branches: 
      - main
      - gh-pages
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.12.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3

      - name: Clean Python cache
        run: python -m pip cache purge
        
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          pip install -r requirements.txt  # Corrected the filename

      - name: Build Flask Application
        run: |
          python freeze.py

      - name: Collect Static files
        run: |
          mkdir -p build/web
          cp -r static build/web
          cp -r templates build/web

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: web-build-artifact
          path: build/web

  deploy:
    needs: build 

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
