name: Web Build + Deployment to GitHub Pages 

on:
  # Runs on push to any of the below branches
  push:
    branches: 
      - main
      - gh-pages
  # Runs on pull request events that target one of the below branches
  pull_request:
    branches: 
      - main
      - gh-pages

  # Allows you to run this workflow manually from the Actions tab of the repository
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false


  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clean Python cache
      run: |
        python -m pip cache purge
      
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.3

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Build Flask Application
      run: |
            export GITHUB_REPOSITORY_USER=${GITHUB_REPOSITORY%/*}
            export GITHUB_REPOSITORY_PROJECT=${GITHUB_REPOSITORY#*/}
            flask run --port=5000 --host=0.0.0.0

    - name: Collect Static files
      run: |
        mkdir -p build/web
        cp -r static build/web
        cp -r templates build/web
        
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: web-build-artifact  # the name of the artifact
        path: build/web

  deploy:
    needs: build  # wait for the "build" job to get done before executing this "deploy" job

    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'  # deploy only on push
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
        
